### ISSUE TITLE
[功能请求] SD-WebUI的脚本插件。

### ISSUE THREAD

**Issue by RedDestiny** [7eu7d7/ML-Danbooru#1]
大佬不考虑整合到 SD-WebUI吗？写个脚本配合wd-tagger的插件使用模型。

**Comment by catboxanon** [comment]
https://github.com/toriato/stable-diffusion-webui-wd14-tagger/pull/77

**Comment by IrisRainbowNeko** [comment]
做插件了 https://github.com/7eu7d7/ML-Danbooru-webui
